[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "reality_mesa"
version = "0.1.0"

requires-python = ">=3.12,<3.13"


dependencies = [
    "mediapipe>=0.10,<0.11",
    "norfair>=2.3,<3",
    "numpy>=1.26,<2",
    "opencv-contrib-python>=4.9,<5",
    "pygame-ce"
    "sentence-transformers>=5.3.0,<5.4.0"
    "openai"
    "requests"
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0",
]

[tool.setuptools.packages.find]
where = ["src"]